### ISSUE TITLE
Support Django 3.0

### ISSUE THREAD

**Issue by ChrisBurch** [evenicoulddoit/django-rest-framework-serializer-extensions#34]
Django 3.0 officially removes the django.utils.six module, causing this library to crash with errors like:

```
    from rest_framework_serializer_extensions.utils import (
  File "....../lib/python3.8/site-packages/rest_framework_serializer_extensions/utils.py", line 6, in <module>
    from django.utils import six
ImportError: cannot import name 'six' from 'django.utils' (....../lib/python3.8/site-packages/django/utils/__init__.py)
```

**Comment by evenicoulddoit** [comment]
Thanks for the suggested fix, and for raising in general. I wonder however if it would be better to altogether drop support for Python 2. Otherwise the `six` imports would add an additional dependency, and to be backwards compatible we'd potentially also need to wrap the imports in a try-clause, first attempting the `django.utils` variant.

Will ponder this. I'm no longer actively using Django, so don't foresee features inbound for this library. Given that, it might be safe to just drop support for Py2 altogether, and bump the version?

**Comment by ChrisBurch** [comment]
No problem, thanks for the quick response! I think that makes a lot of sense, especially given the Python 2 EOL is in a few weeks, and that Django/DRF both dropped support for Python 2 a while ago. I actually first implemented this PR by dropping Python 2, will just push those changes here when I'm at my computer in the morning

**Comment by evenicoulddoit** [comment]
Great - thanks again for the heads up :)

**Comment by ChrisBurch** [comment]
Pushed changes -- let me know what you think!

**Comment by evenicoulddoit** [comment]
@ChrisBurch 2.0.0 published to PyPI :)

**Comment by ChrisBurch** [comment]
Woot! Thanks @evenicoulddoit
